import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Layout/Header";
import AppProvider from "@/context/AppProvider";
import { Toaster } from "@/Components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
        <AppProvider>
          <body>
           <main className="max-w-8xl mx-auto ">
             <Toaster richColors position="top-right-center"  />
            <Header/>
            {children}
           </main>
          </body>
        </AppProvider>
    </html>
  );
}
